import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BT05 from "./BT/BT05/page";
import BT06 from "./BT/BT06/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BT05 />
        <BT06 />
        {children}
      </body>
    </html>
  );
}
